(define (problem transportation2) 
    (:domain transportation)
    (:objects T1 T2 C1 C2 C3 L1 L2 L3 P1 P2 F1 F2 F3 F4 F5
    )

    (:init
        ; Objects
        (truck T1)
        (truck T2)
        (capacity C1)
        (capacity C2)
        (capacity C3)
        (location L1)
        (location L2)
        (location L3)
        (package P1)
        (package P2)
        (fuel F1)
        (fuel F2)
        (fuel F3)
        (fuel F4)
        (fuel F5)
        ; Constants
        (road L1 L2)
        (road L2 L1)
        (road L1 L3)
        (road L3 L1)
        ; Variables
        (capacity-empty C1)
        (capacity-empty C2)
        (capacity-empty C3)
        (truck-capacity T1 C1)
        (truck-capacity T2 C2)
        (truck-capacity T2 C3)
        (truck-at T1 L1)
        (truck-at T2 L1)
        (package-at P1 L2)
        (package-at P2 L2)
        (fuel-at F1 L1)
        (fuel-at F2 L3)
        (fuel-at F3 L3)
        (fuel-at F4 L3)
        (fuel-at F5 L3)
    )

    (:goal (and
            (package-at P1 L3)
            (package-at P2 L3)
        )
    )
)
